export const updateOrganizationKey = [
  'name',
  'vatOrPan',
  'officeContactNumber',
  'officeAddress1',
  'officeAddress2',
  'officeCity',
  'officeState',
  'officeZip',
  'officeCountry',
  'officeBio',
  'officePayRate',
  'officePayType',
  'officeEngagement',
  'officePayCurrency',
];
